### ISSUE TITLE
Hi 请你提供个截图看下呗

### ISSUE THREAD

**Issue by wen2204** [kagol/juejin-markdown-theme-devui-blue#1]
请帮忙提供一个主题的截图看下

**Comment by kagol** [comment]
@wen2204 我在之前提的PR描述中有截图的。
[https://github.com/xitu/juejin-markdown-themes/pull/110](https://github.com/xitu/juejin-markdown-themes/pull/110)

## 引用

![image](https://user-images.githubusercontent.com/9566362/152367343-34fcb990-c1c6-4893-8c6d-4d4248266bd5.png)

## 标题 h1-h6

![image](https://user-images.githubusercontent.com/9566362/152368984-75770716-8960-47f0-90a8-90a28e18f3f8.png)

## 列表

![image](https://user-images.githubusercontent.com/9566362/152370083-cf613a3e-1e5a-46aa-9e10-fa820bff1c23.png)

![image](https://user-images.githubusercontent.com/9566362/152371415-8558f49b-48bf-4dc3-a6e7-90272ed140d8.png)

## 链接

![image](https://user-images.githubusercontent.com/9566362/152370167-76104e47-bc44-436d-9738-a9ec43d83bb8.png)

## 表格

![image](https://user-images.githubusercontent.com/9566362/152369215-441c8f21-413e-40f4-a378-6120e3c059f3.png)

## 任务列表

![image](https://user-images.githubusercontent.com/9566362/152369407-188ff94d-c728-41c7-b371-7cd9dbf33ea4.png)

**Comment by wen2204** [comment]
非常不错，好评，东西不秀出来看不到效果

**Comment by kagol** [comment]
> 非常不错，好评，东西不秀出来看不到效果

@wen2204 我今天在掘金网站的MD编辑器页面测试，发现一个任务列表样式问题（该问题我在[主题预览地址](https://juejin-markdown-themes.netlify.app/)中验证过是没问题的），已提PR解决：[https://github.com/xitu/juejin-markdown-themes/pull/117](https://github.com/xitu/juejin-markdown-themes/pull/117)
